require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CannonsController do

  # This should return the minimal set of attributes required to create a valid
  # Cannon. As you add validations to Cannon, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cannons as @cannons" do
      cannon = Cannon.create! valid_attributes
      get :index
      assigns(:cannons).should eq([cannon])
    end
  end

  describe "GET show" do
    it "assigns the requested cannon as @cannon" do
      cannon = Cannon.create! valid_attributes
      get :show, :id => cannon.id.to_s
      assigns(:cannon).should eq(cannon)
    end
  end

  describe "GET new" do
    it "assigns a new cannon as @cannon" do
      get :new
      assigns(:cannon).should be_a_new(Cannon)
    end
  end

  describe "GET edit" do
    it "assigns the requested cannon as @cannon" do
      cannon = Cannon.create! valid_attributes
      get :edit, :id => cannon.id.to_s
      assigns(:cannon).should eq(cannon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cannon" do
        expect {
          post :create, :cannon => valid_attributes
        }.to change(Cannon, :count).by(1)
      end

      it "assigns a newly created cannon as @cannon" do
        post :create, :cannon => valid_attributes
        assigns(:cannon).should be_a(Cannon)
        assigns(:cannon).should be_persisted
      end

      it "redirects to the created cannon" do
        post :create, :cannon => valid_attributes
        response.should redirect_to(Cannon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cannon as @cannon" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cannon.any_instance.stub(:save).and_return(false)
        post :create, :cannon => {}
        assigns(:cannon).should be_a_new(Cannon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cannon.any_instance.stub(:save).and_return(false)
        post :create, :cannon => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cannon" do
        cannon = Cannon.create! valid_attributes
        # Assuming there are no other cannons in the database, this
        # specifies that the Cannon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cannon.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cannon.id, :cannon => {'these' => 'params'}
      end

      it "assigns the requested cannon as @cannon" do
        cannon = Cannon.create! valid_attributes
        put :update, :id => cannon.id, :cannon => valid_attributes
        assigns(:cannon).should eq(cannon)
      end

      it "redirects to the cannon" do
        cannon = Cannon.create! valid_attributes
        put :update, :id => cannon.id, :cannon => valid_attributes
        response.should redirect_to(cannon)
      end
    end

    describe "with invalid params" do
      it "assigns the cannon as @cannon" do
        cannon = Cannon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cannon.any_instance.stub(:save).and_return(false)
        put :update, :id => cannon.id.to_s, :cannon => {}
        assigns(:cannon).should eq(cannon)
      end

      it "re-renders the 'edit' template" do
        cannon = Cannon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cannon.any_instance.stub(:save).and_return(false)
        put :update, :id => cannon.id.to_s, :cannon => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cannon" do
      cannon = Cannon.create! valid_attributes
      expect {
        delete :destroy, :id => cannon.id.to_s
      }.to change(Cannon, :count).by(-1)
    end

    it "redirects to the cannons list" do
      cannon = Cannon.create! valid_attributes
      delete :destroy, :id => cannon.id.to_s
      response.should redirect_to(cannons_url)
    end
  end

end
